### ISSUE TITLE
req_llm 1.1.0 fails to compile with zoi 0.14.0

### ISSUE THREAD

**Issue by andreasronge** [agentjido/req_llm#295]
## Description

`req_llm 1.1.0` fails to compile when `zoi` resolves to version 0.14.0.

## Error

```
error: Zoi.Types.Object.__struct__/1 is undefined, cannot expand struct Zoi.Types.Object. Make sure the struct name is correct. If the struct name exists and is correct but it still cannot be found, you likely have cyclic module usage in your code
     │
 287 │   defp inject_zoi_metadata(%Zoi.Types.Object{meta: meta, fields: fields}, json) do
     │                            ^
     │
     └─ lib/req_llm/schema.ex:287:28: ReqLLM.Schema.inject_zoi_metadata/2


== Compilation error in file lib/req_llm/schema.ex ==
** (CompileError) lib/req_llm/schema.ex: cannot compile module ReqLLM.Schema (errors have been logged)
```

## Cause

`req_llm 1.1.0` declares `zoi ~> 0.10` as a dependency, but `Zoi.Types.Object` was removed in `zoi 0.11.0`. The struct no longer exists in zoi 0.11+.

## Environment

- Elixir 1.19.3
- OTP 28
- zoi 0.14.0 (resolved via Hex)

## Suggestion

Either:
1. Pin zoi to `~> 0.10.0` (not `~> 0.10`) to avoid incompatible versions, or
2. Update the code to use the new zoi API

**Comment by mikehostetler** [comment]
Thanks - noticed this a few hours ago - we will get it fixed and ship a new patch release very shortly

**Comment by mikehostetler** [comment]
Updated `main` to fix this - should be good now!
