### ISSUE TITLE
[Bug]: Cannot compile on Elixir 1.19.5

### ISSUE THREAD

**Issue by manhvu** [agentjido/req_llm#716]
### Bug Description

Define `record` is reserved in new version of Elixir/Erlang. Need to update this for support new version of Elixir/Erlang.

Compiling log:
mix compile
==> req_llm
Compiling 149 files (.ex)

== Compilation error in file lib/req_llm/open_telemetry/metrics.ex ==
** (Kernel.TypespecError) lib/req_llm/open_telemetry/metrics.ex:99: type record/0 is a built-in type and it cannot be redefined
    (elixir 1.19.5) lib/kernel/typespec.ex:992: Kernel.Typespec.compile_error/2
    (stdlib 8.0) lists.erl:2465: :lists.foldl/3
    (elixir 1.19.5) lib/kernel/typespec.ex:230: Kernel.Typespec.translate_typespecs_for_module/2
could not compile dependency :req_llm, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile req_llm --force", update it with "mix deps.update req_llm" or clean it with "mix deps.clean req_llm"

### Reproduction Code

```elixir
Cannot compile dependency.
```

### Expected Behavior

Can run on latest version of Elixir/Erlang.

### Actual Behavior

Not supported.

### Environment

Elixir 1.19.5, OTP 29
